# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Relax"
license = "MIT"
licenselink = "https://github.com/decached/hugo-relax/blob/master/LICENSE.md"
description = "A minimalist, free and open-source Hugo theme for creators, developers and casual bloggers."
homepage = "https://decached.com/code/hugo-relax"
tags = ["minimalist", "blog"]
features = ["google tag manager", "responsive"]
min_version = 0.18

[author]
  name = "Akash Kothawale"
  homepage = "https://decached.com"
